Repository purestorage/helm-charts, pull requests merged in 2020-01, with the labels that each got.

#149 Add the per-volume FS Options document
  docs/csi-filesystem-options.md
  operator-csi-plugin/README.md
  pure-csi/README.md
Labels: :book: documentation

#152 Remove old beta reference in default storageclass definition
  pure-csi/templates/storageclass.yaml
  pure-k8s-plugin/templates/storageclass.yaml
Labels: :cloud: k8s

#151 k8s Api updates for 1.16+
  operator-csi-plugin/install.sh
  operator-k8s-plugin/install.sh
  pure-csi/templates/_helpers.tpl
  pure-csi/templates/node.yaml
  pure-csi/templates/provisioner.yaml
  pure-csi/templates/rbac.yaml
  pure-k8s-plugin/templates/_helpers.tpl
  pure-k8s-plugin/templates/clusterrolebinding.yaml
  pure-k8s-plugin/templates/pure-flex-daemon.yaml
  pure-k8s-plugin/templates/pure-provisioner.yaml
Labels: :beetle:bug, :cloud: k8s

#150 StorageClass FS Options support
  pure-csi/templates/storageclass.yaml
  pure-csi/values.yaml
Labels: :bulb: enhancement, :cloud: k8s

#153 Add documentation for storage classes
  docs/custom-storageclasses.md
  operator-csi-plugin/README.md
  pure-csi/README.md
Labels: :book: documentation

#156 Convert helm-chart defaultMountOpt from a slice to a string
  pure-csi/templates/node.yaml
Labels: :beetle:bug

#162 Update helm v3 commands in README.md
  pure-csi/README.md
  pure-k8s-plugin/README.md
Labels: :book: documentation

#165 Fix typo in snapshot docs
  docs/csi-snapshot-clones.md
Labels: :book: documentation

#164 Added an orchestrator basePath value to the CSI chart
  pure-csi/README.md
  pure-csi/templates/node.yaml
  pure-csi/values.yaml
Labels: :beetle:bug, :bulb: enhancement
